package org.com.zhump.mssp.entity;

public class MsspRolePermission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mssp_role_permission.id
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mssp_role_permission.role_id
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mssp_role_permission.permission_id
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    private Integer permissionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mssp_role_permission.id
     *
     * @return the value of mssp_role_permission.id
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mssp_role_permission.id
     *
     * @param id the value for mssp_role_permission.id
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mssp_role_permission.role_id
     *
     * @return the value of mssp_role_permission.role_id
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mssp_role_permission.role_id
     *
     * @param roleId the value for mssp_role_permission.role_id
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mssp_role_permission.permission_id
     *
     * @return the value of mssp_role_permission.permission_id
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    public Integer getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mssp_role_permission.permission_id
     *
     * @param permissionId the value for mssp_role_permission.permission_id
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    public void setPermissionId(Integer permissionId) {
        this.permissionId = permissionId;
    }
}