package org.com.zhump.mssp.entity;

import java.util.Date;

public class MsspPermission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mssp_permission.id
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mssp_permission.system_id
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    private Long systemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mssp_permission.pid
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    private Long pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mssp_permission.name
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mssp_permission.type
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mssp_permission.permission_value
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    private String permissionValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mssp_permission.uri
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    private String uri;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mssp_permission.icon
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mssp_permission.status
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mssp_permission.create_time
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mssp_permission.orders
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    private Long orders;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mssp_permission.update_time
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mssp_permission.id
     *
     * @return the value of mssp_permission.id
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mssp_permission.id
     *
     * @param id the value for mssp_permission.id
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mssp_permission.system_id
     *
     * @return the value of mssp_permission.system_id
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    public Long getSystemId() {
        return systemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mssp_permission.system_id
     *
     * @param systemId the value for mssp_permission.system_id
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    public void setSystemId(Long systemId) {
        this.systemId = systemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mssp_permission.pid
     *
     * @return the value of mssp_permission.pid
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mssp_permission.pid
     *
     * @param pid the value for mssp_permission.pid
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mssp_permission.name
     *
     * @return the value of mssp_permission.name
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mssp_permission.name
     *
     * @param name the value for mssp_permission.name
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mssp_permission.type
     *
     * @return the value of mssp_permission.type
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mssp_permission.type
     *
     * @param type the value for mssp_permission.type
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mssp_permission.permission_value
     *
     * @return the value of mssp_permission.permission_value
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    public String getPermissionValue() {
        return permissionValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mssp_permission.permission_value
     *
     * @param permissionValue the value for mssp_permission.permission_value
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    public void setPermissionValue(String permissionValue) {
        this.permissionValue = permissionValue == null ? null : permissionValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mssp_permission.uri
     *
     * @return the value of mssp_permission.uri
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    public String getUri() {
        return uri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mssp_permission.uri
     *
     * @param uri the value for mssp_permission.uri
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    public void setUri(String uri) {
        this.uri = uri == null ? null : uri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mssp_permission.icon
     *
     * @return the value of mssp_permission.icon
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mssp_permission.icon
     *
     * @param icon the value for mssp_permission.icon
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mssp_permission.status
     *
     * @return the value of mssp_permission.status
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mssp_permission.status
     *
     * @param status the value for mssp_permission.status
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mssp_permission.create_time
     *
     * @return the value of mssp_permission.create_time
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mssp_permission.create_time
     *
     * @param createTime the value for mssp_permission.create_time
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mssp_permission.orders
     *
     * @return the value of mssp_permission.orders
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    public Long getOrders() {
        return orders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mssp_permission.orders
     *
     * @param orders the value for mssp_permission.orders
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    public void setOrders(Long orders) {
        this.orders = orders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mssp_permission.update_time
     *
     * @return the value of mssp_permission.update_time
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mssp_permission.update_time
     *
     * @param updateTime the value for mssp_permission.update_time
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}