package org.com.zhump.mssp.entity;

import java.util.Date;

public class MsspOrganization {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mssp_organization.ID
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mssp_organization.PID
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    private Long pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mssp_organization.NAME
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mssp_organization.REMARK
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mssp_organization.CREATE_TIME
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mssp_organization.UPDATE_TIME
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mssp_organization.ID
     *
     * @return the value of mssp_organization.ID
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mssp_organization.ID
     *
     * @param id the value for mssp_organization.ID
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mssp_organization.PID
     *
     * @return the value of mssp_organization.PID
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mssp_organization.PID
     *
     * @param pid the value for mssp_organization.PID
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mssp_organization.NAME
     *
     * @return the value of mssp_organization.NAME
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mssp_organization.NAME
     *
     * @param name the value for mssp_organization.NAME
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mssp_organization.REMARK
     *
     * @return the value of mssp_organization.REMARK
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mssp_organization.REMARK
     *
     * @param remark the value for mssp_organization.REMARK
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mssp_organization.CREATE_TIME
     *
     * @return the value of mssp_organization.CREATE_TIME
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mssp_organization.CREATE_TIME
     *
     * @param createTime the value for mssp_organization.CREATE_TIME
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mssp_organization.UPDATE_TIME
     *
     * @return the value of mssp_organization.UPDATE_TIME
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mssp_organization.UPDATE_TIME
     *
     * @param updateTime the value for mssp_organization.UPDATE_TIME
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}