package org.com.zhump.mssp.entity;

public class MsspUserOrganization {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mssp_user_organization.id
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mssp_user_organization.user_id
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mssp_user_organization.organization_id
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    private Integer organizationId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mssp_user_organization.id
     *
     * @return the value of mssp_user_organization.id
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mssp_user_organization.id
     *
     * @param id the value for mssp_user_organization.id
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mssp_user_organization.user_id
     *
     * @return the value of mssp_user_organization.user_id
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mssp_user_organization.user_id
     *
     * @param userId the value for mssp_user_organization.user_id
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mssp_user_organization.organization_id
     *
     * @return the value of mssp_user_organization.organization_id
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    public Integer getOrganizationId() {
        return organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mssp_user_organization.organization_id
     *
     * @param organizationId the value for mssp_user_organization.organization_id
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    public void setOrganizationId(Integer organizationId) {
        this.organizationId = organizationId;
    }
}