package org.com.zhump.mssp.entity;

import java.util.Date;

public class MsspSystem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mssp_system.id
     *
     * @mbggenerated Sat Aug 22 14:43:21 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mssp_system.icon
     *
     * @mbggenerated Sat Aug 22 14:43:21 CST 2020
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mssp_system.banner
     *
     * @mbggenerated Sat Aug 22 14:43:21 CST 2020
     */
    private String banner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mssp_system.theme
     *
     * @mbggenerated Sat Aug 22 14:43:21 CST 2020
     */
    private String theme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mssp_system.basepath
     *
     * @mbggenerated Sat Aug 22 14:43:21 CST 2020
     */
    private String basepath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mssp_system.status
     *
     * @mbggenerated Sat Aug 22 14:43:21 CST 2020
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mssp_system.name
     *
     * @mbggenerated Sat Aug 22 14:43:21 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mssp_system.title
     *
     * @mbggenerated Sat Aug 22 14:43:21 CST 2020
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mssp_system.description
     *
     * @mbggenerated Sat Aug 22 14:43:21 CST 2020
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mssp_system.create_time
     *
     * @mbggenerated Sat Aug 22 14:43:21 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mssp_system.update_time
     *
     * @mbggenerated Sat Aug 22 14:43:21 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mssp_system.orders
     *
     * @mbggenerated Sat Aug 22 14:43:21 CST 2020
     */
    private Long orders;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mssp_system.id
     *
     * @return the value of mssp_system.id
     *
     * @mbggenerated Sat Aug 22 14:43:21 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mssp_system.id
     *
     * @param id the value for mssp_system.id
     *
     * @mbggenerated Sat Aug 22 14:43:21 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mssp_system.icon
     *
     * @return the value of mssp_system.icon
     *
     * @mbggenerated Sat Aug 22 14:43:21 CST 2020
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mssp_system.icon
     *
     * @param icon the value for mssp_system.icon
     *
     * @mbggenerated Sat Aug 22 14:43:21 CST 2020
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mssp_system.banner
     *
     * @return the value of mssp_system.banner
     *
     * @mbggenerated Sat Aug 22 14:43:21 CST 2020
     */
    public String getBanner() {
        return banner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mssp_system.banner
     *
     * @param banner the value for mssp_system.banner
     *
     * @mbggenerated Sat Aug 22 14:43:21 CST 2020
     */
    public void setBanner(String banner) {
        this.banner = banner == null ? null : banner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mssp_system.theme
     *
     * @return the value of mssp_system.theme
     *
     * @mbggenerated Sat Aug 22 14:43:21 CST 2020
     */
    public String getTheme() {
        return theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mssp_system.theme
     *
     * @param theme the value for mssp_system.theme
     *
     * @mbggenerated Sat Aug 22 14:43:21 CST 2020
     */
    public void setTheme(String theme) {
        this.theme = theme == null ? null : theme.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mssp_system.basepath
     *
     * @return the value of mssp_system.basepath
     *
     * @mbggenerated Sat Aug 22 14:43:21 CST 2020
     */
    public String getBasepath() {
        return basepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mssp_system.basepath
     *
     * @param basepath the value for mssp_system.basepath
     *
     * @mbggenerated Sat Aug 22 14:43:21 CST 2020
     */
    public void setBasepath(String basepath) {
        this.basepath = basepath == null ? null : basepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mssp_system.status
     *
     * @return the value of mssp_system.status
     *
     * @mbggenerated Sat Aug 22 14:43:21 CST 2020
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mssp_system.status
     *
     * @param status the value for mssp_system.status
     *
     * @mbggenerated Sat Aug 22 14:43:21 CST 2020
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mssp_system.name
     *
     * @return the value of mssp_system.name
     *
     * @mbggenerated Sat Aug 22 14:43:21 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mssp_system.name
     *
     * @param name the value for mssp_system.name
     *
     * @mbggenerated Sat Aug 22 14:43:21 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mssp_system.title
     *
     * @return the value of mssp_system.title
     *
     * @mbggenerated Sat Aug 22 14:43:21 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mssp_system.title
     *
     * @param title the value for mssp_system.title
     *
     * @mbggenerated Sat Aug 22 14:43:21 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mssp_system.description
     *
     * @return the value of mssp_system.description
     *
     * @mbggenerated Sat Aug 22 14:43:21 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mssp_system.description
     *
     * @param description the value for mssp_system.description
     *
     * @mbggenerated Sat Aug 22 14:43:21 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mssp_system.create_time
     *
     * @return the value of mssp_system.create_time
     *
     * @mbggenerated Sat Aug 22 14:43:21 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mssp_system.create_time
     *
     * @param createTime the value for mssp_system.create_time
     *
     * @mbggenerated Sat Aug 22 14:43:21 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mssp_system.update_time
     *
     * @return the value of mssp_system.update_time
     *
     * @mbggenerated Sat Aug 22 14:43:21 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mssp_system.update_time
     *
     * @param updateTime the value for mssp_system.update_time
     *
     * @mbggenerated Sat Aug 22 14:43:21 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mssp_system.orders
     *
     * @return the value of mssp_system.orders
     *
     * @mbggenerated Sat Aug 22 14:43:21 CST 2020
     */
    public Long getOrders() {
        return orders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mssp_system.orders
     *
     * @param orders the value for mssp_system.orders
     *
     * @mbggenerated Sat Aug 22 14:43:21 CST 2020
     */
    public void setOrders(Long orders) {
        this.orders = orders;
    }
}