package org.com.zhump.mssp.entity;

public class MsspPermission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mssp_permission.id
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mssp_permission.system_id
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    private Integer systemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mssp_permission.pid
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mssp_permission.name
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mssp_permission.type
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mssp_permission.permission_value
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    private String permissionValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mssp_permission.uri
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    private String uri;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mssp_permission.icon
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mssp_permission.status
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mssp_permission.ctime
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    private Long ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mssp_permission.orders
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    private Long orders;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mssp_permission.id
     *
     * @return the value of mssp_permission.id
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mssp_permission.id
     *
     * @param id the value for mssp_permission.id
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mssp_permission.system_id
     *
     * @return the value of mssp_permission.system_id
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    public Integer getSystemId() {
        return systemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mssp_permission.system_id
     *
     * @param systemId the value for mssp_permission.system_id
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    public void setSystemId(Integer systemId) {
        this.systemId = systemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mssp_permission.pid
     *
     * @return the value of mssp_permission.pid
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mssp_permission.pid
     *
     * @param pid the value for mssp_permission.pid
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mssp_permission.name
     *
     * @return the value of mssp_permission.name
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mssp_permission.name
     *
     * @param name the value for mssp_permission.name
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mssp_permission.type
     *
     * @return the value of mssp_permission.type
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mssp_permission.type
     *
     * @param type the value for mssp_permission.type
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mssp_permission.permission_value
     *
     * @return the value of mssp_permission.permission_value
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    public String getPermissionValue() {
        return permissionValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mssp_permission.permission_value
     *
     * @param permissionValue the value for mssp_permission.permission_value
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    public void setPermissionValue(String permissionValue) {
        this.permissionValue = permissionValue == null ? null : permissionValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mssp_permission.uri
     *
     * @return the value of mssp_permission.uri
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    public String getUri() {
        return uri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mssp_permission.uri
     *
     * @param uri the value for mssp_permission.uri
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    public void setUri(String uri) {
        this.uri = uri == null ? null : uri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mssp_permission.icon
     *
     * @return the value of mssp_permission.icon
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mssp_permission.icon
     *
     * @param icon the value for mssp_permission.icon
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mssp_permission.status
     *
     * @return the value of mssp_permission.status
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mssp_permission.status
     *
     * @param status the value for mssp_permission.status
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mssp_permission.ctime
     *
     * @return the value of mssp_permission.ctime
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    public Long getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mssp_permission.ctime
     *
     * @param ctime the value for mssp_permission.ctime
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    public void setCtime(Long ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mssp_permission.orders
     *
     * @return the value of mssp_permission.orders
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    public Long getOrders() {
        return orders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mssp_permission.orders
     *
     * @param orders the value for mssp_permission.orders
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    public void setOrders(Long orders) {
        this.orders = orders;
    }
}