package org.com.zhump.mssp.entity;

public class MsspUserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mssp_user_role.ID
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mssp_user_role.USER_ID
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mssp_user_role.ROLE_ID
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    private Long roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mssp_user_role.ID
     *
     * @return the value of mssp_user_role.ID
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mssp_user_role.ID
     *
     * @param id the value for mssp_user_role.ID
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mssp_user_role.USER_ID
     *
     * @return the value of mssp_user_role.USER_ID
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mssp_user_role.USER_ID
     *
     * @param userId the value for mssp_user_role.USER_ID
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mssp_user_role.ROLE_ID
     *
     * @return the value of mssp_user_role.ROLE_ID
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mssp_user_role.ROLE_ID
     *
     * @param roleId the value for mssp_user_role.ROLE_ID
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }
}