server:
  port: 4011
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  zipkin:
    base-url: http://127.0.0.1:9411/
    enabled: true
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0
  redis:
    database: 0
    host: 10.10.203.21
    #host: 192.168.112.100
    port: 9001
    #port: 7001
    password: 123456
    lettuce:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 10000
    timeout: 5000

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:6011/eureka/
logging:
  level:
    org.springframework.cloud.gateway: debug
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always