server:
  port: 9411
spring:
  application:
    name: zipkin_server
#  datasource:
#    url: jdbc:mysql://192.169.2.63:3306/zhump_blog
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.jdbc.Driver
  sleuth:
    enabled: false
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:6011/eureka/
management:
  metrics:
    web:
      server:
        auto-time-requests: false
zipkin:
  storage:
    StorageComponent: elasticsearch
    type: elasticsearch
    elasticsearch:
      #hosts: 192.168.112.100:9200
      hosts: 10.10.203.21:9200
      cluster: elasticsearchCluster #Cluster
      index: zipkin-server
      index-shards: 5
      index-replicas: 1