server:
  port: 8011
spring:
  application:
    name: dsp-service-impl
#  zipkin:
#    base-url: http://127.0.0.1:9411/
#    enabled: true
#    sender:
#      type: web
#  sleuth:
#    sampler:
#      probability: 1.0
  profiles:
    active: dspDev
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:6011/eureka/

feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false