package org.com.zhump.mssp.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.com.zhump.mssp.entity.MsspRolePermission;
import org.com.zhump.mssp.entity.MsspRolePermissionExample;

public interface MsspRolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mssp_role_permission
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    int countByExample(MsspRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mssp_role_permission
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    int deleteByExample(MsspRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mssp_role_permission
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mssp_role_permission
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    int insert(MsspRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mssp_role_permission
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    int insertSelective(MsspRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mssp_role_permission
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    List<MsspRolePermission> selectByExample(MsspRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mssp_role_permission
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    MsspRolePermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mssp_role_permission
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    int updateByExampleSelective(@Param("record") MsspRolePermission record, @Param("example") MsspRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mssp_role_permission
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    int updateByExample(@Param("record") MsspRolePermission record, @Param("example") MsspRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mssp_role_permission
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    int updateByPrimaryKeySelective(MsspRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mssp_role_permission
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    int updateByPrimaryKey(MsspRolePermission record);
}