package org.com.zhump.mssp.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.com.zhump.mssp.entity.MsspRole;
import org.com.zhump.mssp.entity.MsspRoleExample;

public interface MsspRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mssp_role
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    int countByExample(MsspRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mssp_role
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    int deleteByExample(MsspRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mssp_role
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mssp_role
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    int insert(MsspRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mssp_role
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    int insertSelective(MsspRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mssp_role
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    List<MsspRole> selectByExample(MsspRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mssp_role
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    MsspRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mssp_role
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    int updateByExampleSelective(@Param("record") MsspRole record, @Param("example") MsspRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mssp_role
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    int updateByExample(@Param("record") MsspRole record, @Param("example") MsspRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mssp_role
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    int updateByPrimaryKeySelective(MsspRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mssp_role
     *
     * @mbggenerated Sat Aug 22 15:49:28 CST 2020
     */
    int updateByPrimaryKey(MsspRole record);
}