package org.com.zhump.mssp.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.com.zhump.mssp.entity.MsspSystem;
import org.com.zhump.mssp.entity.MsspSystemExample;

public interface MsspSystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mssp_system
     *
     * @mbggenerated Sat Aug 22 14:43:21 CST 2020
     */
    int countByExample(MsspSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mssp_system
     *
     * @mbggenerated Sat Aug 22 14:43:21 CST 2020
     */
    int deleteByExample(MsspSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mssp_system
     *
     * @mbggenerated Sat Aug 22 14:43:21 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mssp_system
     *
     * @mbggenerated Sat Aug 22 14:43:21 CST 2020
     */
    int insert(MsspSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mssp_system
     *
     * @mbggenerated Sat Aug 22 14:43:21 CST 2020
     */
    int insertSelective(MsspSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mssp_system
     *
     * @mbggenerated Sat Aug 22 14:43:21 CST 2020
     */
    List<MsspSystem> selectByExample(MsspSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mssp_system
     *
     * @mbggenerated Sat Aug 22 14:43:21 CST 2020
     */
    MsspSystem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mssp_system
     *
     * @mbggenerated Sat Aug 22 14:43:21 CST 2020
     */
    int updateByExampleSelective(@Param("record") MsspSystem record, @Param("example") MsspSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mssp_system
     *
     * @mbggenerated Sat Aug 22 14:43:21 CST 2020
     */
    int updateByExample(@Param("record") MsspSystem record, @Param("example") MsspSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mssp_system
     *
     * @mbggenerated Sat Aug 22 14:43:21 CST 2020
     */
    int updateByPrimaryKeySelective(MsspSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mssp_system
     *
     * @mbggenerated Sat Aug 22 14:43:21 CST 2020
     */
    int updateByPrimaryKey(MsspSystem record);
}