package org.com.zhump.mssp.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.com.zhump.mssp.entity.MsspUser;
import org.com.zhump.mssp.entity.MsspUserExample;

public interface MsspUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mssp_user
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    int countByExample(MsspUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mssp_user
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    int deleteByExample(MsspUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mssp_user
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mssp_user
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    int insert(MsspUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mssp_user
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    int insertSelective(MsspUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mssp_user
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    List<MsspUser> selectByExample(MsspUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mssp_user
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    MsspUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mssp_user
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    int updateByExampleSelective(@Param("record") MsspUser record, @Param("example") MsspUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mssp_user
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    int updateByExample(@Param("record") MsspUser record, @Param("example") MsspUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mssp_user
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    int updateByPrimaryKeySelective(MsspUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mssp_user
     *
     * @mbggenerated Wed Aug 05 17:13:02 CST 2020
     */
    int updateByPrimaryKey(MsspUser record);
}