spring:
  datasource:
    #url: jdbc:mysql://192.168.112.100:3306/zhump?allowMultiQueries=true&amp;useUnicode=true&amp;zeroDateTimeBehavior=convertToNull&amp;characterEncoding=UTF-8
<<<<<<< HEAD
    #url: jdbc:mysql://192.168.112.100:3306/mboss
    url: jdbc:mysql://192.169.2.63:3306/zhump_blog
=======
    url: jdbc:mysql://192.168.112.100:3306/mboss
    #url: jdbc:mysql://192.169.2.63:3306/zhump_blog
>>>>>>> 2da8331fbc0f54ffb1a8ad1c7ba0e135d47d8a6d
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
<<<<<<< HEAD
    host: 10.10.203.21
    password: 123456
    port: 9001
=======
    #host: 10.10.203.21
    host: 192.168.112.100
    password: 123456
    #port: 9001
    port: 7001
>>>>>>> 2da8331fbc0f54ffb1a8ad1c7ba0e135d47d8a6d
    lettuce:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 10000
    timeout: 5000
mybatis:
    config-location: classpath:mybatis/mybatis-config.xml
    mapper-locations: classpath:mybatis/mapper/*.xml
