#spring:
#  datasource:
#    #url: jdbc:mysql://192.168.112.100:3306/zhump?allowMultiQueries=true&amp;useUnicode=true&amp;zeroDateTimeBehavior=convertToNull&amp;characterEncoding=UTF-8
#    url: jdbc:mysql://192.168.112.100:3306/mboss
#    #url: jdbc:mysql://192.169.2.63:3306/zhump_blog
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.jdbc.Driver
#  redis:
#    #host: 10.10.203.21
#    host: 192.168.112.100
#    password: 123456
#    #port: 9001
#    port: 7001
#    lettuce:
#      pool:
#        max-active: 100
#        max-idle: 10
#        max-wait: 10000
#    timeout: 5000
#mybatis:
#    config-location: classpath:mybatis/mybatis-config.xml
#    mapper-locations: classpath:mybatis/mapper/*.xml
